### ISSUE TITLE
How to use `RN-General-Calendars` for Shamsi/Jalali Date ?

### ISSUE THREAD

**Issue by blackhair** [rghorbani/react-native-general-calendars#1]
Hello and say Thank u for this powerful package.
I've just develop a reservation application for Android and IOS. 
I need a clean and fast datePicker like this package, but i want to use `Shamsi/Jalali` date.
How can i set `RN-General-Calendars` to jalali moment ?

**Comment by rghorbani** [comment]
Hi,
Just use the type parameter and set it to type="jalaali"
for more reference visit [here](https://github.com/rghorbani/react-native-general-calendars#basic-parameters)
Apparently the documentation need more work
