### ISSUE TITLE
OnDayPress selected date is not highlighted 

### ISSUE THREAD

**Issue by Ash-faq** [rghorbani/react-native-general-calendars#17]
When try to select the other date its not get highlighted even current date

**Comment by rghorbani** [comment]
Hi @Ash-faq,
Highlighting is your responsibility by using `current` and `markedDates` props.

**Comment by Ash-faq** [comment]
@rghorbani i have given current it doesn't work.
but when i give markedDate= { date: {selected: true}} it works
and i need to show makedDate with dot and when i click on that date i need to highlight the date
