### ISSUE TITLE
Issue with re-render

### ISSUE THREAD

**Issue by brlocky** [rghorbani/react-native-general-calendars#19]
After onDayPress and changing component state, the calendar list does not re-render.

Video example
https://monosnap.com/file/XIqCU55VnNFNtsqnsf5hs5WZ9J52EY

I try'ed in several ways to paste the code in a way that you could see, but looks like github WYSYWYG is not prepared to accept code 🌊 

`

onDayPress(date) {
        console.log('Selected day : ')
        console.log(date)
        const selectedDate = date.dateString

        let marked = true
        if (this.state.markedDates[selectedDate]) {
            // Already in marked dates, so reverse current marked state
            marked = !this.state.markedDates[selectedDate].selected
        }

        // Create a new object using object property spread since it should be immutable
        // Reading: https://davidwalsh.name/merge-objects
        const updatedMarkedDates = { ...this.state.markedDates, ...{ [selectedDate]: { 'selected': marked } } }

        this.setState({
            selectedDate: selectedDate,
            markedDates: updatedMarkedDates,
        })
    }`

**Comment by rghorbani** [comment]
Hi,
Is your problem fixed or it's still happening?

**Comment by brlocky** [comment]
> Hi,
> Is your problem fixed or it's still happening?

Hi, the problem is solved.
It was an issue with a function binding

**Comment by brlocky** [comment]
Hi,

Actually is a bit buggy still, in 2 weeks we will need to refactor our
calendar.

try to enforce on the constructor function binding.

```
this.myFunction = this.myFunction.bind(this)
```

at the time that was the fix



Joe Attard-Owen <notifications@github.com> escreveu no dia quarta,
23/01/2019 à(s) 23:27:

**Comment by Joeao** [comment]
I didn't realise that this plug-in was a fork of https://github.com/wix/react-native-calendars, so I switched to that and the problem was solved.
