### ISSUE TITLE
same as https://github.com/wix/react-native-calendars

### ISSUE THREAD

**Issue by sibelius** [rghorbani/react-native-general-calendars#2]
How is this lib different from https://github.com/wix/react-native-calendars?

**Comment by tautvilas** [comment]
Hello, I am maintainer of react-native-calendars, I think it is not legal to release your package without reference to WIX and overriding our MIT license.

**Comment by rghorbani** [comment]
@sibelius This package implements Jalaali (Shamsi) calendar as well as the Gregorian calendar.
It also uses momentjs one of the best time libraries available which gives developers more option to customize the their locale

**Comment by rghorbani** [comment]
Hi @tautvilas 
As the MIT license states the use, change, modification and distribution of the code is free of charge.
The packages uses the architecture implemented by you but uses momentjs for date library which resulted in serious changes to coding. It also implements Jalaali calendar as well which resulted in more change.
On the other hand I have forked and made improvements to code and created pull requests to wix's other libraries and never even got a feedback and watch my work stay there.
However I will change the authors section. I appreciate the work you guys are doing.

**Comment by tautvilas** [comment]
I'm fine that there would be a forked version of module, however it should not violate MIT license and leave reference to original copyright notice. Thanks

https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

**Comment by tautvilas** [comment]
Also found some info here:

https://hashnode.com/post/can-i-fork-a-repo-having-mit-licence-and-build-my-own-opensource-product-cj9k06kft007gylwtnmpr70i3

**Comment by tautvilas** [comment]
Thanks, looks good. I don't mind README too much, however the MIT license should reflect original author. This question answers how to do it:

https://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

**Comment by rghorbani** [comment]
@tautvilas done.

**Comment by tautvilas** [comment]
looks great, thanks!

**Comment by smooJitter** [comment]
Yes, because it can be confusing
