### ISSUE TITLE
this calendar is not designed for selecting Birthday ??

### ISSUE THREAD

**Issue by hoseineghbal** [rghorbani/react-native-general-calendars#21]
hello 

is possible to surf between  years fast in this Calendar ?? 

my user wanna select birthday but how with this component ???

``<CalendarList
                    // Calendar type (gregorian, jalaali). Default = gregorian
                    type='jalaali'
                    onDayPress={(day, localDay) => this.onDateChange(day)}
                    // Max amount of months allowed to scroll to the past. Default = 50
                    pastScrollRange={50}
                    // Max amount of months allowed to scroll to the future. Default = 50
                    futureScrollRange={50}
                    // Enable or disable scrolling of calendar list
                    scrollEnabled={true}
                    // Enable or disable vertical scroll indicator. Default = false
                    showScrollIndicator={true}
                />``

**Comment by rghorbani** [comment]
It's not actually.
But you can define custom `onPressArrowLeft` and `onPressArrowRight ` functions and a little imagination should do the work.
