### ISSUE TITLE
Selected Date Style

### ISSUE THREAD

**Issue by sagarpatel8384** [rghorbani/react-native-general-calendars#6]
I can't seem to get the current selected date to show a blue (or any color) dot around the date. My code is:

`
class AddChildForm extends Component<Props, State> {
  constructor(props) {
    super(props);
    this.state = { dob: new Date(), dobModal: true };
  }

  handleDateChange = (dob) => {
    this.setState({ dob, dobModal: false });
  }

  handleDOBModal = () => {
    this.setState({ dobModal: true });
  }

  render() {
    const { name, dob, gender, dobModal } = this.state;

    return (
      <KeyboardAvoidingView behavior="position" enabled contentContainerStyle={styles.keyboardContainer}>
        <View style={styles.bottomHalfContainer}>
          <View style={styles.formContainer}>
            {/* DOB MODAL */}
            <Modal
              animationType="slide"
              transparent={false}
              visible={dobModal}
            >
              <View style={{ marginTop: 22, flex: 1 }}>
                <Calendar
                  markingStyle="period"
                  monthFormat="MMMM YYYY"
                  current={dob}
                  onDayPress={this.handleDateChange}
                  firstDay={1}
                />
              </View>
            </Modal>
          </View>
        </View>
      </KeyboardAvoidingView>
    );
  }
}
`

The currently selected date doesn't seem to work with no styles defined or with this:

`
                  theme={{
                    textSectionTitleColor: '#b6c1cd',
                    selectedDayBackgroundColor: '#00adf5',
                    selectedDayTextColor: '#ffffff',
                  }}
`

**Comment by sagarpatel8384** [comment]
Got it to work with some hackery. Not sure if this is the intended way of showing a marking on the selected date.

`
                <Calendar
                  monthFormat="MMMM YYYY"
                  **markedDates={{ [dateString]: { selected: true } }}**
                  current={dateString}
                  onDayPress={this.handleDateChange}
                  firstDay={1}
                />
`

**Comment by rghorbani** [comment]
It is in some way. Do you still have a problem?
