### ISSUE TITLE
agenda support?

### ISSUE THREAD

**Issue by h4m3d66** [rghorbani/react-native-general-calendars#7]
I can not use agenda with type="jalaali" and it is english. Is agenda supported?

**Comment by rghorbani** [comment]
@h4m3d66 That is why I have not updated the description. There are still some kinks to figure out. You are welcome to create a Pull Request.

**Comment by rghorbani** [comment]
@h4m3d66 That is why I have not updated the description. There are still some kinks to figure out. You are welcome to create a Pull Request.

**Comment by rghorbani** [comment]
@h4m3d66 That is why I have not updated the description. There are still some kinks to figure out. You are welcome to create a Pull Request.

**Comment by rghorbani** [comment]
@h4m3d66 That is why I have not updated the description. There are still some kinks to figure out. You are welcome to create a Pull Request.
