### ISSUE TITLE
افزودن agenda

### ISSUE THREAD

**Issue by mr-siadati** [rghorbani/react-native-general-calendars#8]
سلام و خیلی متشکر از زحمتی که کشیدی بابت شمسی کردن تقویم این کامپوننت

اگر ممکن هست زود تر agenda رو هم اضافه کن

**Comment by rghorbani** [comment]
@mr-siadati Actually I'm a little busy right now and don't have the time. Most of the code is done but there are some bugs to sort out. You are welcome to make a pull request.

**Comment by hadimostafapour** [comment]
@mr-siadati Hi,   you can use  react-native-calendars-persian package instead that supports Agenda.
[react-native-calendars-persian](https://github.com/hadimostafapour/react-native-calendars-persian)

@rghorbani Thanks for your great job dude.

**Comment by hadimostafapour** [comment]
@rghorbani I try to help others like you! It's open source, be kind buddy ;)

**Comment by rghorbani** [comment]
@hadimostafapour It's not right to advertise your module on someone else's repository, especially when it is in the same field.

**Comment by rghorbani** [comment]
@hadimostafapour I put a lot of time on making these modules and contributing to other repos despite my work. How would you like if I do the same?

**Comment by hadimostafapour** [comment]
@rghorbani I'm sorry, but I don't think like you. Sorry again.
Keep up the good work ❤️
